spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  application:
    name: COMMON-PRIVODER

server:
  port: 8003
  max-http-header-size: 4048576 #Request header is too large异常解决
  
eureka:
  instance:
    hostname: localhsot
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
